# Generated by Django 2.2.6 on 2019-11-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='time_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.TimeState'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.TimeState'),
        ),
    ]
