# Generated by Django 2.2.6 on 2019-11-17 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20191117_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='time_state',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_state',
        ),
        migrations.AddField(
            model_name='reactions',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 42, 6, 234611, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 42, 6, 234059, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TimeState',
        ),
    ]
