# Generated by Django 2.2.7 on 2019-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20191117_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='changed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='tickets.SupportOfficer'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='changed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='tickets.SupportOfficer'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
